experiment_2a1:
  one_prompt_model: "gpt-4o-mini-2024-07-18"
  fix_retries: 0
experiment_2a2:
  one_prompt_model: "gpt-4o-2024-08-06"
  fix_retries: 0
experiment_2b1:
  one_prompt_model: "gpt-4o-mini-2024-07-18"
  fix_retries: 1
experiment_2b2:
  one_prompt_model: "gpt-4o-2024-08-06"
  fix_retries: 1